# SPDX-License-Identifier: LGPL-2.1-or-later
# Arch surface config - linux-surface from the linux-surface pacman repo

[Content]
Repositories=
        id:linux-surface
        url:https://pkg.surfacelinux.com/arch/linux-surface.repo

Packages=
        linux-surface
        linux-surface-headers
        iptsd
        libwacom
        surface-control

RemovePackages=
        linux
        linux-headers
