# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Architecture=x86-64

[Content]
Packages=
        # signed EFI binary for UEFI capsule updates, which fwupd only
        # recommends; the package name carries the architecture
        fwupd-amd64-signed
