# SPDX-License-Identifier: LGPL-2.1-or-later
# Fedora surface config - pulls in the linux-surface kernel and iptsd from COPR

[Content]
Repositories=
        id:linux-surface
        url:https://pkg.surfacelinux.com/fedora/linux-surface.repo

Packages=
        kernel-surface
        iptsd
        libwacom-surface
        surface-control

# The surface kernel replaces the stock kernel; remove the base one to avoid
# having two boot entries on the ESP.
RemovePackages=
        kernel
        kernel-core
        kernel-modules
        kernel-modules-core
        kernel-modules-extra
