# SPDX-License-Identifier: LGPL-2.1-or-later
# Debian surface config - uses the linux-surface apt repo for the patched kernel

[Content]
Repositories=
        id:linux-surface
        url:https://pkg.surfacelinux.com/debian/linux-surface.list
        Architectures:amd64
        SignedBy=/usr/share/keyrings/linux-surface.gpg

Packages=
        linux-image-surface
        linux-headers-surface
        iptsd
        libwacom
        firmware-iwlwifi
        firmware-intel-sound

# Drop the generic kernel in favour of the surface one
RemovePackages=
        linux-image-amd64
        linux-image-generic
