# SPDX-License-Identifier: LGPL-2.1-or-later
# iptsd configuration for Surface touchscreen / pen daemon
# See: https://github.com/linux-surface/iptsd

[Touch]
DisableOnStylus = false

[Stylus]
DisableTouch = false
