# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=fedora

[Content]
Packages=
        fontawesome-6-brands-fonts
        fontawesome-6-free-fonts
        fprintd-pam
        gnome-keyring-pam
        gvfs-smb
        plymouth-system-theme
        polkit
        sddm-wayland-sway
        sway-config-fedora
        Thunar
        thunar-archive-plugin
        tuned-switcher
        xorg-x11-server-Xwayland
