# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
ToolsTreeDistribution=fedora
ToolsTreeRelease=44

[Build]
ToolsTreeSandboxTrees=../../systemd.gpg:/usr/share/pki/rpm-gpg/systemd.gpg
                      44.repo:/etc/yum.repos.d/systemd.repo
