# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=debian

[Content]
Packages=
        fonts-font-awesome
        fprintd
        gvfs-backends
        libpam-gnome-keyring
        thunar
        thunar-archive-plugin
        xwayland
