# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=opensuse

[Distribution]
Release=tumbleweed
Repositories=non-oss

[Config]
Dependencies=initrd

[Content]
Initrds=%O/initrd
Packages=
        aaa_base
        bash
        bpftool
        ca-certificates
        ca-certificates-mozilla
        coreutils
        cracklib-dict-small
        cryptsetup
        curl
        device-mapper
        distribution-gpg-keys
        efibootmgr
        filesystem
        git-core
        glibc-locale-base
        gzip
        kernel-default
        kernel-firmware-all
        libcurl-mini4
        libtss2-tcti-device0
        lsb-release
        netcfg
        openssl
        openSUSE-build-key
        openSUSE-release
        patterns-base-base
        pam
        pam_pwquality
        procps
        shadow
        sbsigntools
        sdbootutil
        systemd-boot
        systemd-container
        systemd-experimental
        systemd-networkd
        systemd-portable
        systemd-resolved
        systemd-ukify
        timezone
        tpm2.0-tools
        tpm2-0-tss
        user(nobody)
        vim
        virt-firmware
        veritysetup
        xz
        zypper

VolatilePackages=
        libsystemd0
        libudev1
        systemd
        systemd-boot
        systemd-container
        systemd-doc
        systemd-experimental
        systemd-homed
        systemd-journal-remote
        systemd-lang
        systemd-networkd
        systemd-portable
        systemd-resolved
        systemd-sysvcompat
        systemd-testsuite
        systemd-ukify
        udev
