# SPDX-License-Identifier: LGPL-2.1-or-later

# Requires desktop profile

[Content]
Packages=
        blueman
        dunst
        foot
        grim
        gvfs
        imv
        kanshi
        lxqt-policykit
        network-manager-applet
        pavucontrol
        pinentry-gnome3
        playerctl
        pulseaudio-utils
        rofi
        rofimoji
        sddm
        slurp
        sway
        swaybg
        swayidle
        swaylock
        system-config-printer
        waybar
        wev
        wl-clipboard
        wlr-randr
        wlsunset
        xarchiver
        xdg-desktop-portal-gtk
        xdg-desktop-portal-wlr
