# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=opensuse

[Content]
# Main pcrlock files has been move from experimental to udev package but some
# needed files are still in systemd-experimental.
Packages=
    systemd-experimental
