# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=debian

[Content]
Packages=
        alsa-topology-conf
        alsa-ucm-conf
        debconf
        desktop-base
        firmware-amd-graphics
        firmware-iwlwifi
        firmware-linux
        firmware-mediatek
        firmware-sof-signed
        fonts-adobe-sourcesans3
        fonts-noto-color-emoji
        fonts-noto-core
        fonts-noto-mono
        gstreamer1.0-libav
        gstreamer1.0-plugins-ugly
        kbd
        libsecret-tools
        libyubikey-udev
        locales-all
        mesa-vulkan-drivers
        modemmanager
        network-manager
        pipewire-audio
        plymouth-themes
        steam-devices
        tuned-ppd
        va-driver-all
        wpasupplicant

InitrdVolatilePackages=
        systemd-container
        systemd-cryptsetup
        systemd-resolved
